version: "3"
services:
  db:
    image: "mysql:5.7"
    volumes:
      - "./data:/var/lib/mysql"
    restart: $RESTART
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
  wordpress:
    image: "nothingspare/oakridge-wordpress-debugging:dev"
    depends_on:
      - db
    ports:
      - "$WP_PORT:80"
    restart: $RESTART
    volumes:
      - "./startup.sh:/usr/local/bin/startup.sh"
      - "./install.sh:/usr/local/bin/install.sh"
      - "./.env:/usr/local/bin/env.sh"
    environment:
      WORDPRESS_DB_HOST: db:$MYSQL_PORT
      WORDPRESS_DB_USER: $MYSQL_USERNAME
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_TABLE_PREFIX: $WP_PREFIX
    entrypoint: "startup.sh"
    command: ["apache2-foreground"]